language: bash
env:
  - BATS_VERSION=v0.4.0
  - BATS_VERSION=v1.0.0
before_install:
  - ./script/install-bats.sh
  - git clone --depth 1 https://github.com/ztombol/bats-support ../bats-support
before_script:
  - export PATH="${HOME}/.local/bin:${PATH}"
script:
  - if [ "${BATS_VERSION}" = "v1.0.0" ]; then ! bats test; else bats test; fi
